# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import tracking_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='percentage',
            field=models.IntegerField(validators=[tracking_system.models.validate_range]),
        ),
    ]
