# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_system', '0002_auto_20171030_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='due_date',
            name='list',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='list',
            name='fall_due_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='list',
            name='winter_due_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='process',
            name='feedback',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(choices=[('FALL', 'Fall'), ('WINTER', 'Winter')], max_length=20),
        ),
        migrations.DeleteModel(
            name='due_date',
        ),
    ]
