# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import tracking_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_system', '0005_auto_20171122_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='mark',
            field=models.IntegerField(validators=[tracking_system.models.validate_range]),
        ),
    ]
