# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_system', '0006_auto_20171122_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='fall_due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='winter_due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('PEND', 'Pending'), ('DONE', 'Done'), ('OVER', 'OVer Due')], default='PEND', max_length=4),
        ),
    ]
