# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import tracking_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_system', '0007_auto_20171122_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='actual_mark',
            field=models.IntegerField(blank=True, validators=[tracking_system.models.validate_range]),
        ),
    ]
